package Minicompilador;

/* The following code was generated by JFlex 1.4.3 on 06/05/24, 07:50 */

import static Minicompilador.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 06/05/24, 07:50 from the specification file
 * <tt>C:/Users/JorgeEAJ/Documents/NetBeansProjects/JFlexNetbeans/src/jflexnetbeans/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\3\1\43\1\6\2\0"+
    "\1\55\1\47\1\0\1\57\1\60\1\53\1\51\1\66\1\52\1\67"+
    "\1\4\12\2\1\46\1\65\1\42\1\40\1\41\1\45\1\0\22\1"+
    "\1\36\7\1\1\63\1\0\1\64\1\54\1\56\1\0\1\7\1\10"+
    "\1\14\1\26\1\17\1\30\1\33\1\23\1\24\1\1\1\21\1\16"+
    "\1\31\1\20\1\15\1\32\1\1\1\13\1\11\1\12\1\25\1\34"+
    "\1\35\1\27\1\22\1\37\1\61\1\50\1\62\1\44\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\22\2\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\4\1\40\30\2\1\41\1\2\1\42\15\2"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\13\2\1\64\11\2\1\65\4\2\1\66\2\2"+
    "\1\67\4\2\1\70\14\2\1\71\1\72\1\73\3\2"+
    "\1\74\7\2\1\75\1\2\1\76\1\2\1\77\4\2"+
    "\1\100\1\101\1\102\2\2\1\103\16\2\1\104\1\2"+
    "\1\105\3\2\1\106\1\2\1\107\4\2\1\110\1\111"+
    "\2\2\1\112\1\2\1\113\1\114\1\2\1\115\10\2"+
    "\1\116\1\117\1\120\2\2\1\121\3\2\1\122\4\2"+
    "\1\123\2\2\1\124\1\2\1\125\1\126\2\2\1\127"+
    "\2\2\1\130\1\2\1\131\6\2\1\132\1\2\1\133"+
    "\1\134\1\2\1\135\4\2\1\136\3\2\1\137\1\140"+
    "\1\141\1\2\1\142\1\143\1\2\1\144\1\145\2\2"+
    "\1\146\4\2\1\147\1\2\1\150\1\2\1\151\1\2"+
    "\1\152\1\2\1\153\1\154\1\2\1\155";

  private static int [] zzUnpackAction() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\70\0\340\0\70\0\70"+
    "\0\u0118\0\u0150\0\u0188\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0"+
    "\0\u02d8\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460"+
    "\0\u0498\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\70\0\70"+
    "\0\70\0\u05e8\0\u0620\0\u0658\0\u0690\0\u06c8\0\u0700\0\u0738"+
    "\0\160\0\70\0\70\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\u0770\0\70\0\u07a8\0\u07e0\0\u0818\0\u0850"+
    "\0\u0888\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10"+
    "\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0"+
    "\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\160\0\u0ce8\0\u0d20\0\u0d58"+
    "\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18"+
    "\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8\0\70\0\70\0\u1030\0\70"+
    "\0\u1068\0\70\0\70\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\70\0\70\0\70\0\u10a0\0\u10d8\0\u1110"+
    "\0\u1148\0\u1180\0\u11b8\0\u11f0\0\u1228\0\u1260\0\u1298\0\u12d0"+
    "\0\160\0\u1308\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u1458"+
    "\0\u1490\0\u14c8\0\160\0\u1500\0\u1538\0\u1570\0\u15a8\0\160"+
    "\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730\0\160"+
    "\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\u18b8\0\u18f0"+
    "\0\u1928\0\u1960\0\u1998\0\u19d0\0\70\0\u1a08\0\70\0\u1a40"+
    "\0\u1a78\0\u1ab0\0\160\0\u1ae8\0\u1b20\0\u1b58\0\u1b90\0\u1bc8"+
    "\0\u1c00\0\u1c38\0\160\0\u1c70\0\160\0\u1ca8\0\160\0\u1ce0"+
    "\0\u1d18\0\u1d50\0\u1d88\0\160\0\160\0\160\0\u1dc0\0\u1df8"+
    "\0\160\0\u1e30\0\u1e68\0\u1ea0\0\u1ed8\0\u1f10\0\u1f48\0\u1f80"+
    "\0\u1fb8\0\u1ff0\0\u2028\0\u2060\0\u2098\0\u20d0\0\u2108\0\160"+
    "\0\u2140\0\160\0\u2178\0\u21b0\0\u21e8\0\70\0\u2220\0\160"+
    "\0\u2258\0\u2290\0\u22c8\0\u2300\0\160\0\160\0\u2338\0\u2370"+
    "\0\u23a8\0\u23e0\0\160\0\160\0\u2418\0\160\0\u2450\0\u2488"+
    "\0\u24c0\0\u24f8\0\u2530\0\u2568\0\u25a0\0\u25d8\0\160\0\160"+
    "\0\u2610\0\u2648\0\u2680\0\u26b8\0\u26f0\0\u2728\0\u2760\0\160"+
    "\0\u2798\0\u27d0\0\u2808\0\u2840\0\160\0\u2878\0\u28b0\0\160"+
    "\0\u28e8\0\160\0\160\0\u2920\0\u2958\0\160\0\u2990\0\u29c8"+
    "\0\160\0\u2a00\0\160\0\u2a38\0\u2a70\0\u2aa8\0\u2ae0\0\u2b18"+
    "\0\u2b50\0\160\0\u2b88\0\160\0\160\0\u2bc0\0\160\0\u2bf8"+
    "\0\u2c30\0\u2c68\0\u2ca0\0\160\0\u2cd8\0\u2d10\0\u2d48\0\160"+
    "\0\160\0\160\0\u2d80\0\160\0\160\0\u2db8\0\160\0\160"+
    "\0\u2df0\0\u2e28\0\160\0\u2e60\0\u2e98\0\u2ed0\0\u2f08\0\160"+
    "\0\u2f40\0\160\0\u2f78\0\160\0\u2fb0\0\160\0\u2fe8\0\160"+
    "\0\160\0\u3020\0\160";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\3\3\1\23\1\3\1\24\1\3\1\25\1\3"+
    "\1\26\1\27\1\30\1\31\1\32\1\3\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\71\0\2\3"+
    "\4\0\31\3\16\0\1\3\13\0\1\4\71\0\1\63"+
    "\33\0\1\64\30\0\2\3\4\0\1\3\1\65\27\3"+
    "\16\0\1\3\12\0\2\3\4\0\4\3\1\66\1\3"+
    "\1\67\4\3\1\70\15\3\16\0\1\3\12\0\2\3"+
    "\4\0\3\3\1\71\7\3\1\72\1\73\1\3\1\74"+
    "\7\3\1\75\2\3\16\0\1\3\12\0\2\3\4\0"+
    "\4\3\1\76\7\3\1\77\14\3\16\0\1\3\12\0"+
    "\2\3\4\0\10\3\1\100\20\3\16\0\1\3\12\0"+
    "\2\3\4\0\1\101\5\3\1\102\1\103\4\3\1\104"+
    "\14\3\16\0\1\3\12\0\2\3\4\0\16\3\1\105"+
    "\12\3\16\0\1\3\12\0\2\3\4\0\6\3\1\106"+
    "\22\3\16\0\1\3\12\0\2\3\4\0\7\3\1\107"+
    "\10\3\1\110\10\3\16\0\1\3\12\0\2\3\4\0"+
    "\1\111\7\3\1\112\5\3\1\113\12\3\16\0\1\3"+
    "\12\0\2\3\4\0\11\3\1\114\7\3\1\115\1\116"+
    "\6\3\16\0\1\3\12\0\2\3\4\0\6\3\1\117"+
    "\1\3\1\120\20\3\16\0\1\3\12\0\2\3\4\0"+
    "\1\121\5\3\1\122\1\123\5\3\1\124\13\3\16\0"+
    "\1\3\12\0\2\3\4\0\1\125\3\3\1\126\11\3"+
    "\1\127\12\3\16\0\1\3\12\0\2\3\4\0\6\3"+
    "\1\130\22\3\16\0\1\3\12\0\2\3\4\0\6\3"+
    "\1\131\22\3\16\0\1\3\12\0\2\3\4\0\14\3"+
    "\1\132\14\3\16\0\1\3\12\0\2\3\4\0\3\3"+
    "\1\133\7\3\1\134\15\3\16\0\1\3\51\0\1\135"+
    "\67\0\1\136\1\137\66\0\1\140\1\0\1\141\65\0"+
    "\1\142\67\0\1\143\6\0\1\144\60\0\1\145\7\0"+
    "\1\146\21\0\1\4\35\0\1\147\10\0\1\150\20\0"+
    "\1\4\35\0\1\151\11\0\1\152\55\0\1\153\67\0"+
    "\1\154\67\0\1\155\27\0\5\63\1\0\62\63\1\0"+
    "\2\3\4\0\2\3\1\156\26\3\16\0\1\3\12\0"+
    "\2\3\4\0\10\3\1\157\20\3\16\0\1\3\12\0"+
    "\2\3\4\0\6\3\1\160\22\3\16\0\1\3\12\0"+
    "\2\3\4\0\3\3\1\161\25\3\16\0\1\3\12\0"+
    "\2\3\4\0\1\162\3\3\1\163\24\3\16\0\1\3"+
    "\12\0\2\3\4\0\11\3\1\164\17\3\16\0\1\3"+
    "\12\0\2\3\4\0\6\3\1\165\22\3\16\0\1\3"+
    "\12\0\2\3\4\0\23\3\1\166\5\3\16\0\1\3"+
    "\12\0\2\3\4\0\15\3\1\167\13\3\16\0\1\3"+
    "\12\0\2\3\4\0\1\170\12\3\1\171\2\3\1\172"+
    "\12\3\16\0\1\3\12\0\2\3\4\0\4\3\1\173"+
    "\10\3\1\174\13\3\16\0\1\3\12\0\2\3\4\0"+
    "\3\3\1\175\25\3\16\0\1\3\12\0\2\3\4\0"+
    "\2\3\1\176\1\177\25\3\16\0\1\3\12\0\2\3"+
    "\4\0\11\3\1\200\17\3\16\0\1\3\12\0\2\3"+
    "\4\0\1\201\30\3\16\0\1\3\12\0\2\3\4\0"+
    "\1\202\30\3\16\0\1\3\12\0\2\3\4\0\3\3"+
    "\1\203\25\3\16\0\1\3\12\0\2\3\4\0\11\3"+
    "\1\204\17\3\16\0\1\3\12\0\2\3\4\0\2\3"+
    "\1\205\26\3\16\0\1\3\12\0\2\3\4\0\3\3"+
    "\1\206\25\3\16\0\1\3\12\0\2\3\4\0\3\3"+
    "\1\207\25\3\16\0\1\3\12\0\2\3\4\0\26\3"+
    "\1\210\2\3\16\0\1\3\12\0\2\3\4\0\7\3"+
    "\1\211\21\3\16\0\1\3\12\0\2\3\4\0\2\3"+
    "\1\212\1\213\25\3\16\0\1\3\12\0\2\3\4\0"+
    "\23\3\1\214\5\3\16\0\1\3\12\0\2\3\4\0"+
    "\16\3\1\215\12\3\16\0\1\3\12\0\2\3\4\0"+
    "\21\3\1\216\7\3\16\0\1\3\12\0\2\3\4\0"+
    "\7\3\1\217\21\3\16\0\1\3\12\0\2\3\4\0"+
    "\4\3\1\220\24\3\16\0\1\3\12\0\2\3\4\0"+
    "\6\3\1\221\22\3\16\0\1\3\12\0\2\3\4\0"+
    "\11\3\1\222\17\3\16\0\1\3\12\0\2\3\4\0"+
    "\5\3\1\223\23\3\16\0\1\3\12\0\2\3\4\0"+
    "\6\3\1\224\6\3\1\225\13\3\16\0\1\3\12\0"+
    "\2\3\4\0\1\3\1\226\27\3\16\0\1\3\12\0"+
    "\2\3\4\0\3\3\1\227\25\3\16\0\1\3\12\0"+
    "\2\3\4\0\7\3\1\230\5\3\1\231\13\3\16\0"+
    "\1\3\12\0\2\3\4\0\15\3\1\232\13\3\16\0"+
    "\1\3\12\0\2\3\4\0\4\3\1\233\24\3\16\0"+
    "\1\3\12\0\2\3\4\0\2\3\1\234\26\3\16\0"+
    "\1\3\51\0\1\235\1\236\66\0\1\237\30\0\2\3"+
    "\4\0\3\3\1\240\25\3\16\0\1\3\12\0\2\3"+
    "\4\0\1\241\30\3\16\0\1\3\12\0\2\3\4\0"+
    "\7\3\1\242\21\3\16\0\1\3\12\0\2\3\4\0"+
    "\10\3\1\243\20\3\16\0\1\3\12\0\2\3\4\0"+
    "\3\3\1\244\25\3\16\0\1\3\12\0\2\3\4\0"+
    "\15\3\1\245\13\3\16\0\1\3\12\0\2\3\4\0"+
    "\5\3\1\246\23\3\16\0\1\3\12\0\2\3\4\0"+
    "\4\3\1\247\24\3\16\0\1\3\12\0\2\3\4\0"+
    "\10\3\1\250\20\3\16\0\1\3\12\0\2\3\4\0"+
    "\3\3\1\251\25\3\16\0\1\3\12\0\2\3\4\0"+
    "\11\3\1\252\17\3\16\0\1\3\12\0\2\3\4\0"+
    "\10\3\1\253\20\3\16\0\1\3\12\0\2\3\4\0"+
    "\6\3\1\254\22\3\16\0\1\3\12\0\2\3\4\0"+
    "\2\3\1\255\26\3\16\0\1\3\12\0\2\3\4\0"+
    "\16\3\1\256\12\3\16\0\1\3\12\0\2\3\4\0"+
    "\10\3\1\257\20\3\16\0\1\3\12\0\2\3\4\0"+
    "\5\3\1\260\23\3\16\0\1\3\12\0\2\3\4\0"+
    "\2\3\1\261\1\262\25\3\16\0\1\3\12\0\2\3"+
    "\4\0\2\3\1\263\26\3\16\0\1\3\12\0\2\3"+
    "\4\0\4\3\1\264\24\3\16\0\1\3\12\0\2\3"+
    "\4\0\24\3\1\265\4\3\16\0\1\3\12\0\2\3"+
    "\4\0\10\3\1\266\20\3\16\0\1\3\12\0\2\3"+
    "\4\0\10\3\1\267\20\3\16\0\1\3\12\0\2\3"+
    "\4\0\15\3\1\270\13\3\16\0\1\3\12\0\2\3"+
    "\4\0\7\3\1\271\21\3\16\0\1\3\12\0\2\3"+
    "\4\0\3\3\1\272\25\3\16\0\1\3\12\0\2\3"+
    "\4\0\10\3\1\273\20\3\16\0\1\3\12\0\2\3"+
    "\4\0\6\3\1\274\1\275\21\3\16\0\1\3\12\0"+
    "\2\3\4\0\1\3\1\276\27\3\16\0\1\3\12\0"+
    "\2\3\4\0\1\277\30\3\16\0\1\3\12\0\2\3"+
    "\4\0\2\3\1\300\26\3\16\0\1\3\12\0\2\3"+
    "\4\0\1\301\30\3\16\0\1\3\12\0\2\3\4\0"+
    "\1\302\30\3\16\0\1\3\12\0\2\3\4\0\12\3"+
    "\1\303\16\3\16\0\1\3\12\0\2\3\4\0\3\3"+
    "\1\304\25\3\16\0\1\3\12\0\2\3\4\0\11\3"+
    "\1\305\13\3\1\306\3\3\16\0\1\3\12\0\2\3"+
    "\4\0\7\3\1\307\21\3\16\0\1\3\12\0\2\3"+
    "\4\0\6\3\1\310\22\3\16\0\1\3\12\0\2\3"+
    "\4\0\1\311\30\3\16\0\1\3\12\0\2\3\4\0"+
    "\17\3\1\312\11\3\16\0\1\3\12\0\2\3\4\0"+
    "\7\3\1\313\21\3\16\0\1\3\12\0\2\3\4\0"+
    "\15\3\1\314\13\3\16\0\1\3\12\0\2\3\4\0"+
    "\3\3\1\315\25\3\16\0\1\3\51\0\1\316\30\0"+
    "\2\3\4\0\4\3\1\317\24\3\16\0\1\3\12\0"+
    "\2\3\4\0\12\3\1\320\16\3\16\0\1\3\12\0"+
    "\2\3\4\0\10\3\1\321\20\3\16\0\1\3\12\0"+
    "\2\3\4\0\15\3\1\322\13\3\16\0\1\3\12\0"+
    "\2\3\4\0\5\3\1\323\23\3\16\0\1\3\12\0"+
    "\2\3\4\0\14\3\1\324\14\3\16\0\1\3\12\0"+
    "\2\3\4\0\3\3\1\325\25\3\16\0\1\3\12\0"+
    "\2\3\4\0\4\3\1\326\24\3\16\0\1\3\12\0"+
    "\2\3\4\0\5\3\1\327\23\3\16\0\1\3\12\0"+
    "\2\3\4\0\2\3\1\330\26\3\16\0\1\3\12\0"+
    "\2\3\4\0\26\3\1\331\2\3\16\0\1\3\12\0"+
    "\2\3\4\0\4\3\1\332\24\3\16\0\1\3\12\0"+
    "\2\3\4\0\14\3\1\333\14\3\16\0\1\3\12\0"+
    "\2\3\4\0\3\3\1\334\25\3\16\0\1\3\12\0"+
    "\2\3\4\0\15\3\1\335\13\3\16\0\1\3\12\0"+
    "\2\3\4\0\2\3\1\336\26\3\16\0\1\3\12\0"+
    "\2\3\4\0\11\3\1\337\17\3\16\0\1\3\12\0"+
    "\2\3\4\0\25\3\1\340\3\3\16\0\1\3\12\0"+
    "\2\3\4\0\1\341\30\3\16\0\1\3\12\0\2\3"+
    "\4\0\4\3\1\342\24\3\16\0\1\3\12\0\2\3"+
    "\4\0\4\3\1\343\24\3\16\0\1\3\12\0\2\3"+
    "\4\0\10\3\1\344\20\3\16\0\1\3\12\0\2\3"+
    "\4\0\7\3\1\345\21\3\16\0\1\3\12\0\2\3"+
    "\4\0\16\3\1\346\12\3\16\0\1\3\12\0\2\3"+
    "\4\0\10\3\1\347\20\3\16\0\1\3\12\0\2\3"+
    "\4\0\3\3\1\350\25\3\16\0\1\3\12\0\2\3"+
    "\4\0\7\3\1\351\21\3\16\0\1\3\12\0\2\3"+
    "\4\0\1\352\30\3\16\0\1\3\12\0\2\3\4\0"+
    "\10\3\1\353\20\3\16\0\1\3\12\0\2\3\4\0"+
    "\3\3\1\354\25\3\16\0\1\3\12\0\2\3\4\0"+
    "\1\355\30\3\16\0\1\3\12\0\2\3\4\0\15\3"+
    "\1\356\13\3\16\0\1\3\12\0\2\3\4\0\3\3"+
    "\1\357\25\3\16\0\1\3\12\0\2\3\4\0\10\3"+
    "\1\360\20\3\16\0\1\3\12\0\2\3\4\0\11\3"+
    "\1\361\17\3\16\0\1\3\12\0\2\3\4\0\10\3"+
    "\1\362\20\3\16\0\1\3\12\0\2\3\4\0\1\363"+
    "\30\3\16\0\1\3\12\0\2\3\4\0\1\364\30\3"+
    "\16\0\1\3\12\0\2\3\4\0\5\3\1\365\23\3"+
    "\16\0\1\3\12\0\2\3\4\0\3\3\1\366\25\3"+
    "\16\0\1\3\12\0\2\3\4\0\4\3\1\367\24\3"+
    "\16\0\1\3\12\0\2\3\4\0\14\3\1\370\14\3"+
    "\16\0\1\3\12\0\2\3\4\0\15\3\1\371\13\3"+
    "\16\0\1\3\12\0\2\3\4\0\2\3\1\372\26\3"+
    "\16\0\1\3\12\0\2\3\4\0\11\3\1\373\17\3"+
    "\16\0\1\3\12\0\2\3\4\0\11\3\1\374\17\3"+
    "\16\0\1\3\12\0\2\3\4\0\17\3\1\375\11\3"+
    "\16\0\1\3\12\0\2\3\4\0\10\3\1\376\20\3"+
    "\16\0\1\3\12\0\2\3\4\0\11\3\1\377\17\3"+
    "\16\0\1\3\12\0\2\3\4\0\21\3\1\u0100\7\3"+
    "\16\0\1\3\12\0\2\3\4\0\3\3\1\u0101\25\3"+
    "\16\0\1\3\12\0\2\3\4\0\22\3\1\u0102\6\3"+
    "\16\0\1\3\12\0\2\3\4\0\10\3\1\u0103\20\3"+
    "\16\0\1\3\12\0\2\3\4\0\7\3\1\u0104\21\3"+
    "\16\0\1\3\12\0\2\3\4\0\7\3\1\u0105\21\3"+
    "\16\0\1\3\12\0\2\3\4\0\24\3\1\u0106\4\3"+
    "\16\0\1\3\12\0\2\3\4\0\5\3\1\u0107\23\3"+
    "\16\0\1\3\12\0\2\3\4\0\7\3\1\u0108\21\3"+
    "\16\0\1\3\12\0\2\3\4\0\3\3\1\u0109\25\3"+
    "\16\0\1\3\12\0\2\3\4\0\5\3\1\u010a\23\3"+
    "\16\0\1\3\12\0\2\3\4\0\15\3\1\u010b\13\3"+
    "\16\0\1\3\12\0\2\3\4\0\24\3\1\u010c\4\3"+
    "\16\0\1\3\12\0\2\3\4\0\22\3\1\u010d\6\3"+
    "\16\0\1\3\12\0\2\3\4\0\5\3\1\u010e\23\3"+
    "\16\0\1\3\12\0\2\3\4\0\11\3\1\u010f\17\3"+
    "\16\0\1\3\12\0\2\3\4\0\21\3\1\u0110\7\3"+
    "\16\0\1\3\12\0\2\3\4\0\6\3\1\u0111\22\3"+
    "\16\0\1\3\12\0\2\3\4\0\10\3\1\u0112\20\3"+
    "\16\0\1\3\12\0\2\3\4\0\16\3\1\u0113\12\3"+
    "\16\0\1\3\12\0\2\3\4\0\2\3\1\u0114\26\3"+
    "\16\0\1\3\12\0\2\3\4\0\5\3\1\u0115\23\3"+
    "\16\0\1\3\12\0\2\3\4\0\1\u0116\30\3\16\0"+
    "\1\3\12\0\2\3\4\0\10\3\1\u0117\20\3\16\0"+
    "\1\3\12\0\2\3\4\0\3\3\1\u0118\25\3\16\0"+
    "\1\3\12\0\2\3\4\0\13\3\1\u0119\15\3\16\0"+
    "\1\3\12\0\2\3\4\0\10\3\1\u011a\20\3\16\0"+
    "\1\3\12\0\2\3\4\0\3\3\1\u011b\25\3\16\0"+
    "\1\3\12\0\2\3\4\0\11\3\1\u011c\17\3\16\0"+
    "\1\3\12\0\2\3\4\0\10\3\1\u011d\20\3\16\0"+
    "\1\3\12\0\2\3\4\0\7\3\1\u011e\21\3\16\0"+
    "\1\3\12\0\2\3\4\0\3\3\1\u011f\25\3\16\0"+
    "\1\3\12\0\2\3\4\0\23\3\1\u0120\5\3\16\0"+
    "\1\3\12\0\2\3\4\0\11\3\1\u0121\17\3\16\0"+
    "\1\3\12\0\2\3\4\0\11\3\1\u0122\17\3\16\0"+
    "\1\3\12\0\2\3\4\0\10\3\1\u0123\20\3\16\0"+
    "\1\3\12\0\2\3\4\0\10\3\1\u0124\20\3\16\0"+
    "\1\3\12\0\2\3\4\0\5\3\1\u0125\23\3\16\0"+
    "\1\3\12\0\2\3\4\0\11\3\1\u0126\17\3\16\0"+
    "\1\3\12\0\2\3\4\0\10\3\1\u0127\20\3\16\0"+
    "\1\3\12\0\2\3\4\0\10\3\1\u0128\20\3\16\0"+
    "\1\3\12\0\2\3\4\0\15\3\1\u0129\13\3\16\0"+
    "\1\3\12\0\2\3\4\0\3\3\1\u012a\25\3\16\0"+
    "\1\3\12\0\2\3\4\0\6\3\1\u012b\22\3\16\0"+
    "\1\3\12\0\2\3\4\0\10\3\1\u012c\20\3\16\0"+
    "\1\3\12\0\2\3\4\0\3\3\1\u012d\25\3\16\0"+
    "\1\3\12\0\2\3\4\0\17\3\1\u012e\11\3\16\0"+
    "\1\3\12\0\2\3\4\0\30\3\1\u012f\16\0\1\3"+
    "\12\0\2\3\4\0\21\3\1\u0130\7\3\16\0\1\3"+
    "\12\0\2\3\4\0\2\3\1\u0131\26\3\16\0\1\3"+
    "\12\0\2\3\4\0\10\3\1\u0132\20\3\16\0\1\3"+
    "\12\0\2\3\4\0\17\3\1\u0133\11\3\16\0\1\3"+
    "\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12376];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\1\1\2\11\26\1\3\11"+
    "\10\1\11\11\1\1\1\11\50\1\2\11\1\1\1\11"+
    "\1\1\14\11\57\1\1\11\1\1\1\11\56\1\1\11"+
    "\145\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public  String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 79: 
          { return PALABRA_RESERVADA_FLOAT;
          }
        case 110: break;
        case 87: 
          { return PALABRA_RESERVADA_NATIVE;
          }
        case 111: break;
        case 13: 
          { return QUESTION;
          }
        case 112: break;
        case 65: 
          { return PALABRA_RESERVADA_LONG;
          }
        case 113: break;
        case 8: 
          { return ASIGNACION;
          }
        case 114: break;
        case 3: 
          { lexeme=yytext();  return INT;
          }
        case 115: break;
        case 30: 
          { return COMA;
          }
        case 116: break;
        case 96: 
          { return PALABRA_RESERVADA_FINALLY;
          }
        case 117: break;
        case 99: 
          { return PALABRA_RESERVADA_PRIVATE;
          }
        case 118: break;
        case 74: 
          { return PALABRA_RESERVADA_THROW;
          }
        case 119: break;
        case 23: 
          { return IZQPAREN;
          }
        case 120: break;
        case 47: 
          { return MENOSIGUAL;
          }
        case 121: break;
        case 105: 
          { return PALABRA_RESERVADA_INTERFACE;
          }
        case 122: break;
        case 43: 
          { return BARRAIGUAL;
          }
        case 123: break;
        case 64: 
          { return PALABRA_RESERVADA_CHAR;
          }
        case 124: break;
        case 28: 
          { return DERCORCH;
          }
        case 125: break;
        case 85: 
          { return PALABRA_RESERVADA_THROWS;
          }
        case 126: break;
        case 46: 
          { return MASMAS;
          }
        case 127: break;
        case 11: 
          { return NEGADO;
          }
        case 128: break;
        case 93: 
          { return PALABRA_RESERVADA_BOOLEAN;
          }
        case 129: break;
        case 4: 
          { /*Ignore*/
          }
        case 130: break;
        case 2: 
          { lexeme=yytext(); return ID;
          }
        case 131: break;
        case 54: 
          { return PALABRA_RESERVADA_NEW;
          }
        case 132: break;
        case 39: 
          { return SHIFTIZQ;
          }
        case 133: break;
        case 53: 
          { return PALABRA_RESERVADA_OUT;
          }
        case 134: break;
        case 72: 
          { return PALABRA_RESERVADA_SHORT;
          }
        case 135: break;
        case 34: 
          { return PALABRA_RESERVADA_DO;
          }
        case 136: break;
        case 57: 
          { return SHIFTDERIGUAL;
          }
        case 137: break;
        case 45: 
          { return MASIGUAL;
          }
        case 138: break;
        case 32: 
          { return DIVIGUAL;
          }
        case 139: break;
        case 104: 
          { return PALABRA_RESERVADA_TRANSIENT;
          }
        case 140: break;
        case 91: 
          { return PALABRA_RESERVADA_STRING;
          }
        case 141: break;
        case 55: 
          { return PALABRA_RESERVADA_INT;
          }
        case 142: break;
        case 19: 
          { return MULT;
          }
        case 143: break;
        case 17: 
          { return MAS;
          }
        case 144: break;
        case 60: 
          { return PALABRA_RESERVADA_BYTE;
          }
        case 145: break;
        case 94: 
          { return PALABRA_RESERVADA_EXTENDS;
          }
        case 146: break;
        case 82: 
          { return PALABRA_RESERVADA_WHILE;
          }
        case 147: break;
        case 44: 
          { return O;
          }
        case 148: break;
        case 48: 
          { return MENOSMENOS;
          }
        case 149: break;
        case 5: 
          { return DIV;
          }
        case 150: break;
        case 102: 
          { return PALABRA_RESERVADA_CONTINUE;
          }
        case 151: break;
        case 76: 
          { return PALABRA_RESERVADA_CONST;
          }
        case 152: break;
        case 1: 
          { return ERROR;
          }
        case 153: break;
        case 29: 
          { return PUNTOYCOMA;
          }
        case 154: break;
        case 88: 
          { return PALABRA_RESERVADA_IMPORT;
          }
        case 155: break;
        case 22: 
          { return GUIONBAJO;
          }
        case 156: break;
        case 61: 
          { return LITERAL_BOOLEANA_T;
          }
        case 157: break;
        case 71: 
          { return PALABRA_RESERVADA_BREAK;
          }
        case 158: break;
        case 38: 
          { return MENORIGUALQ;
          }
        case 159: break;
        case 27: 
          { return IZQCORCH;
          }
        case 160: break;
        case 66: 
          { return PALABRA_RESERVADA_ELSE;
          }
        case 161: break;
        case 92: 
          { return PALABRA_RESERVADA_SYSTEM;
          }
        case 162: break;
        case 109: 
          { return PALABRA_RESERVADA_SYNCHRONIZED;
          }
        case 163: break;
        case 51: 
          { return MODIGUAL;
          }
        case 164: break;
        case 35: 
          { return IGUALDAD;
          }
        case 165: break;
        case 68: 
          { return PALABRA_RESERVADA_GOTO;
          }
        case 166: break;
        case 26: 
          { return DERLLAVE;
          }
        case 167: break;
        case 56: 
          { return PALABRA_RESERVADA_FOR;
          }
        case 168: break;
        case 59: 
          { return SHIFTIZQIGUAL;
          }
        case 169: break;
        case 50: 
          { return CIRCIGUAL;
          }
        case 170: break;
        case 63: 
          { return PALABRA_RESERVADA_CASE;
          }
        case 171: break;
        case 33: 
          { return PALABRA_RESERVADA_IF;
          }
        case 172: break;
        case 73: 
          { return PALABRA_RESERVADA_SUPER;
          }
        case 173: break;
        case 15: 
          { return AMPERSAND;
          }
        case 174: break;
        case 62: 
          { return PALABRA_RESERVADA_THIS;
          }
        case 175: break;
        case 100: 
          { return PALABRA_RESERVADA_ABSTRACT;
          }
        case 176: break;
        case 83: 
          { return PALABRA_RESERVADA_STATIC;
          }
        case 177: break;
        case 37: 
          { return SHIFTDER;
          }
        case 178: break;
        case 75: 
          { return PALABRA_RESERVADA_CATCH;
          }
        case 179: break;
        case 58: 
          { return URSHIFT;
          }
        case 180: break;
        case 49: 
          { return MULTIGUAL;
          }
        case 181: break;
        case 10: 
          { return MENORQ;
          }
        case 182: break;
        case 95: 
          { return PALABRA_RESERVADA_DEFAULT;
          }
        case 183: break;
        case 12: 
          { return COMP;
          }
        case 184: break;
        case 52: 
          { return PALABRA_RESERVADA_TRY;
          }
        case 185: break;
        case 97: 
          { return PALABRA_RESERVADA_PACKAGE;
          }
        case 186: break;
        case 78: 
          { return LITERAL_BOOLEANA_F;
          }
        case 187: break;
        case 20: 
          { return CIRCUNFLEJO;
          }
        case 188: break;
        case 67: 
          { return LITERAL_NULA;
          }
        case 189: break;
        case 36: 
          { return MAYORIGUALQ;
          }
        case 190: break;
        case 24: 
          { return DERPAREN;
          }
        case 191: break;
        case 42: 
          { return Y;
          }
        case 192: break;
        case 41: 
          { return AMPIGUAL;
          }
        case 193: break;
        case 103: 
          { return PALABRA_RESERVADA_VOLATILE;
          }
        case 194: break;
        case 21: 
          { return MODULO;
          }
        case 195: break;
        case 77: 
          { return PALABRA_RESERVADA_CLASS;
          }
        case 196: break;
        case 31: 
          { return PUNTO;
          }
        case 197: break;
        case 101: 
          { return PALABRA_RESERVADA_STRICTFP;
          }
        case 198: break;
        case 16: 
          { return BARRA;
          }
        case 199: break;
        case 18: 
          { return MENOS;
          }
        case 200: break;
        case 69: 
          { return PALABRA_RESERVADA_VOID;
          }
        case 201: break;
        case 80: 
          { return PALABRA_RESERVADA_FINAL;
          }
        case 202: break;
        case 86: 
          { return PALABRA_RESERVADA_RETURN;
          }
        case 203: break;
        case 106: 
          { return PALABRA_RESERVADA_PROTECTED;
          }
        case 204: break;
        case 81: 
          { return PALABRA_RESERVADA_PRINT;
          }
        case 205: break;
        case 70: 
          { return URSHIFTIGUAL;
          }
        case 206: break;
        case 40: 
          { return DISTINTO;
          }
        case 207: break;
        case 25: 
          { return IZQLLAVE;
          }
        case 208: break;
        case 98: 
          { return PALABRA_RESERVADA_PRINTLN;
          }
        case 209: break;
        case 89: 
          { return PALABRA_RESERVADA_DOUBLE;
          }
        case 210: break;
        case 9: 
          { return MAYORQ;
          }
        case 211: break;
        case 84: 
          { return PALABRA_RESERVADA_SWITCH;
          }
        case 212: break;
        case 107: 
          { return PALABRA_RESERVADA_INSTANCEOF;
          }
        case 213: break;
        case 6: 
          { return SALTO;
          }
        case 214: break;
        case 108: 
          { return PALABRA_RESERVADA_IMPLEMENTS;
          }
        case 215: break;
        case 90: 
          { return PALABRA_RESERVADA_PUBLIC;
          }
        case 216: break;
        case 14: 
          { return DOSPUNTOS;
          }
        case 217: break;
        case 7: 
          { return COMILLA_DOB;
          }
        case 218: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
