package Minicompilador;


public enum Token {
    ID,INT,ASSIGN,EQUALS,PLUS,TIMES,MINUS,ERROR,DIV,SALTO,COMILLA_DOB,PALABRA_RESERVADA_ABSTRACT,PALABRA_RESERVADA_BOOLEAN,
    PALABRA_RESERVADA_BREAK,PALABRA_RESERVADA_BYTE,PALABRA_RESERVADA_CASE,PALABRA_RESERVADA_CATCH,PALABRA_RESERVADA_CHAR,
    PALABRA_RESERVADA_CLASS,PALABRA_RESERVADA_CONST,PALABRA_RESERVADA_CONTINUE,PALABRA_RESERVADA_DO,PALABRA_RESERVADA_DOUBLE,
    PALABRA_RESERVADA_ELSE,PALABRA_RESERVADA_EXTENDS,PALABRA_RESERVADA_FINAL,PALABRA_RESERVADA_FINALLY,PALABRA_RESERVADA_FLOAT,
    PALABRA_RESERVADA_FOR,PALABRA_RESERVADA_DEFAULT,PALABRA_RESERVADA_IMPLEMENTS,PALABRA_RESERVADA_IMPORT,PALABRA_RESERVADA_INSTANCEOF,
    PALABRA_RESERVADA_INT,PALABRA_RESERVADA_INTERFACE,PALABRA_RESERVADA_LONG,PALABRA_RESERVADA_NATIVE,PALABRA_RESERVADA_NEW,PALABRA_RESERVADA_GOTO,
    PALABRA_RESERVADA_IF,PALABRA_RESERVADA_OUT,PALABRA_RESERVADA_PUBLIC,PALABRA_RESERVADA_PRINTLN, PALABRA_RESERVADA_SHORT, PALABRA_RESERVADA_SUPER, PALABRA_RESERVADA_SWITCH,
    PALABRA_RESERVADA_STRING, PALABRA_RESERVADA_SYNCHRONIZED, PALABRA_RESERVADA_PACKAGE, PALABRA_RESERVADA_PRIVATE, PALABRA_RESERVADA_PROTECTED, PALABRA_RESERVADA_TRANSIENT, 
    PALABRA_RESERVADA_RETURN, PALABRA_RESERVADA_VOID, PALABRA_RESERVADA_STATIC, PALABRA_RESERVADA_SYSTEM, PALABRA_RESERVADA_WHILE, PALABRA_RESERVADA_THIS, PALABRA_RESERVADA_THROW, 
    PALABRA_RESERVADA_THROWS, PALABRA_RESERVADA_TRY, PALABRA_RESERVADA_VOLATILE, PALABRA_RESERVADA_STRICTFP,ASIGNACION, MAYORQ, MENORQ, NEGADO, COMP, QUESTION, DOSPUNTOS, IGUALDAD, 
    MENORIGUALQ, MAYORIGUALQ, DISTINTO, Y, O, MASMAS, MENOSMENOS, MAS, MENOS, MULT, AMPERSAND, BARRA, CIRCUNFLEJO, MODULO, SHIFTIZQ, SHIFTDER, URSHIFT, MASIGUAL, MENOSIGUAL, MULTIGUAL, 
    DIVIGUAL, AMPIGUAL,BARRAIGUAL, CIRCIGUAL, MODIGUAL, SHIFTIZQIGUAL, SHIFTDERIGUAL, URSHIFTIGUAL, GUIONBAJO,IZQPAREN, DERPAREN, IZQLLAVE, DERLLAVE, IZQCORCH, DERCORCH, PUNTOYCOMA, COMA, PUNTO,
    LITERAL_NULA,LITERAL_BOOLEANA_F,LITERAL_BOOLEANA_T,PALABRA_RESERVADA_PRINT
}
